version: '3.1'

services:

  mysql-mentor:
    image: mysql
    container_name: mysql-mentor
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mentor
      MYSQL_USER: mentor
      MYSQL_PASSWORD: mentor
    ports:
      - 3308:3306
